query allCharacters{
  characters(page: 1) {
      info {
        count
      }
      results {
        id,
        name,
        species,
        gender,
        image,
        episode {
          episode,
        }
    }
  }
}